package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	"fmt"

	"github.com/Andreworoh27/farebook/graph/model"
	"github.com/google/uuid"
)

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, inputPost model.NewPost) (*model.Post, error) {
	post := &model.Post{
		PostID:           uuid.NewString(),
		UserID:           inputPost.UserID,
		Vidio:            inputPost.Vidio,
		Photo:            inputPost.Photo,
		Text:             inputPost.Text,
		PostDate:         inputPost.PostDate,
		VisibilityType:   inputPost.VisibilityType,
		NumberOfComments: inputPost.NumberOfComments,
		NumberOfShares:   inputPost.NumberOfShares,
		NumberOfLikes:    inputPost.NumberOfLikes,
	}

	return post, r.DB.Save(&post).Error
}

// UpdatePost is the resolver for the updatePost field.
func (r *mutationResolver) UpdatePost(ctx context.Context, postID string, inputPost model.NewPost) (*model.Post, error) {
	panic(fmt.Errorf("not implemented: UpdatePost - updatePost"))
}

// DeletePost is the resolver for the deletePost field.
func (r *mutationResolver) DeletePost(ctx context.Context, id string) (*model.Post, error) {
	panic(fmt.Errorf("not implemented: DeletePost - deletePost"))
}

// GetPost is the resolver for the getPost field.
func (r *queryResolver) GetPost(ctx context.Context, postID string) (*model.Post, error) {
	var post *model.Post
	return post, r.DB.First(&post, "post_id = ?", postID).Error
}

// GetAllPost is the resolver for the getAllPost field.
func (r *queryResolver) GetAllPost(ctx context.Context) ([]*model.Post, error) {
	panic(fmt.Errorf("not implemented: GetAllPost - getAllPost"))
}

// GetPostVisibleFriends is the resolver for the getPostVisibleFriends field.
func (r *queryResolver) GetPostVisibleFriends(ctx context.Context, postID string) ([]*model.User, error) {
	panic(fmt.Errorf("not implemented: GetPostVisibleFriends - getPostVisibleFriends"))
}

// GetPostTaggedUsers is the resolver for the getPostTaggedUsers field.
func (r *queryResolver) GetPostTaggedUsers(ctx context.Context, postID string) ([]*model.User, error) {
	panic(fmt.Errorf("not implemented: GetPostTaggedUsers - getPostTaggedUsers"))
}
